apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: frontend
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - frontend.keptnorder-staging.35.205.124.152.nip.io
  - frontend
  http:
  - route:
    - destination:
        host: frontend.keptnorder-staging.svc.cluster.local
