apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: catalog
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - catalog.keptnorder-production.35.205.124.152.nip.io
  - catalog
  http:
  - route:
    - destination:
        host: catalog-canary.keptnorder-production.svc.cluster.local
      weight: 100
    - destination:
        host: catalog-primary.keptnorder-production.svc.cluster.local
